### ISSUE TITLE
I think you should change the name of the repository

### ISSUE THREAD

**Issue by samhstn** [daUnicorns/daunicorns.github.io#21]
Blogsite was a well named repository, maybe name this newspage

**Comment by RobStallion** [comment]
Sorry if I have misunderstood what you meant but Blogsite was the repo we made before we created our GH pages. This repo is not actually called blogsite. @shouston3

**Comment by samhstn** [comment]
The repo is currently called: daunicorns.github.io, I maybe change this to newspage
