### ISSUE TITLE
Synchronous get request

### ISSUE THREAD

**Issue by RachBLondon** [daUnicorns/daunicorns.github.io#25]
Is there a reason for why you did this api call synchronously rather than asychnronously?

**Comment by eliasmalik** [comment]
Should probably use async calls, and consider using event listeners instead of onreadystatechange. Documentation [here](https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest)

**Comment by RobStallion** [comment]
Thanks for the advice. Will look into how we can improve it :+1:
