### ISSUE TITLE
Commenting in filmapi.js file

### ISSUE THREAD

**Issue by samhstn** [daUnicorns/daunicorns.github.io#30]
Consider writing comments explaining what each function does, lines 14-17 and 22-24 in filmapi.js can be written in one line each without creating a single use variable
Maybe delete out the lines which are commented out console.logs

**Comment by eleanorreem** [comment]
have made some comments and removed the single use variables

**Comment by RobStallion** [comment]
@shouston3

**Comment by samhstn** [comment]
Nice thanks, closed
